version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/github.com/Sakamoto0525/payment-app
    ports:
      -  8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: payment_app
